apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: desdemoregistry.azurecr.io/backend:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__mongo
          valueFrom:
            secretKeyRef:
              key: connectionstring
              name: aksdemocosmos
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: desdemoregistry.azurecr.io/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: cache__redis
          valueFrom:
            secretKeyRef:
              key: connectionstring
              name: aksdemoredis
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: isInCluster
          value: "true"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: desdemoregistry.azurecr.io/webserver:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: backend
spec:
  ports:
  - port: 80
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
spec:
  ports:
  - port: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webserver